### PR TITLE
Terraform for EC2 Tagging

### PR DESCRIPTION
**Pull request by bcarranza**
## EC2 Tagging
- It collects information about running instances in the AWS (Amazon Web Services) cloud.
- It retrieves the identity of the AWS account that is executing the code.
- It creates a local variable called "instance_tags" that contains information about the instances and their associated tags.
- It applies the AWS EC2 tag to each instance based on the collected information.

### CODE REVIEW

**Comment by bcarranza** [comment]
@oluojolola 
We need to get @sekka1's  approval, he needs some evidence to achieve the approval, I will create some post in order to you can quote reply every one of them!!

**Comment by bcarranza** [comment]
@oluojolola 
Add in the readme file a description , why we should use this solution? more human stuff!!!!

**Comment by bcarranza** [comment]
@oluojolola Could you add where we are using this branch in gruntwork-infrastructure live project!!?

**Comment by bcarranza** [comment]
@oluojolola  could you add evidence about which are your inputs values to this solution? you can paste here github link whit that portion of code?

**Comment by bcarranza** [comment]
@oluojolola  could you add terragrunt apply log evidence!!?

**Comment by bcarranza** [comment]
@oluojolola  could you posted here the aws console evidence about the outcome to apply this solution? (pictures)

**Comment by oluojolola** [comment]
> @oluojolola Could you add where we are using this branch in gruntwork-infrastructure live project!!?

This will be deployed in All Exactpay AWS Accounts that run their workloads. The first Iteration will be in the dev/p2 account shown below @bcarranza 
 https://github.com/exact-payments/gruntwork-infrastructure-live/tree/master/dev/us-west-2/dev/p2a/ec2-tags

**Comment by oluojolola** [comment]
> @oluojolola could you add terragrunt apply log evidence!!?

Below
Screen Shot 2023-06-20 at 15 01 10
 is the evidence of the Terragrunt apply as requested

**Comment by oluojolola** [comment]
> @oluojolola could you add evidence about which are your inputs values to this solution? you can paste here github link whit that portion of code?

Below Link shows the Input values that is being used by Exact for tagging existing resources in various accounts https://github.com/exact-payments/gruntwork-infrastructure-live/blob/d690a0da719425238de6a7c257ee3fffe72932b6/dev/us-west-2/dev/p2a/EC2-EKS_Tags/terragrunt.hcl#LL63C3-L63C3

**Comment by oluojolola** [comment]
> @oluojolola could you posted here the aws console evidence about the outcome to apply this solution? (pictures)

find below evidence of tags applied in Dev Exactpay account @bcarranza 
image (3)
image (3)

**Pull request merged**
